In [4]:
def divide():
    return 5/0

try:
    divide()
except ZeroDivisionError as ze:
    print("you are dividing a number by ZERO!")
except:
    print("Any other exception")

you are dividing a number by ZERO!


In [9]:
def divide(x, y): 
    try: 
        # Floor Division : Gives only Fractional Part as Answer 
        result = x // y 
        print("Yeah ! Your answer is :", result) 
    except ZeroDivisionError: 
        print("Sorry ! You are dividing by zero ") 
  

divide(5, 0) 

Sorry ! You are dividing by zero 


In [14]:
subject=["Americans","Indians"]
verb=["play","watch"]
objects=["Baseball","Cricket"]

sentence_list = [(sub+" "+ vb + " " + ob) for sub in subject for vb in verb for ob in objects]
for sentences in sentence_list:
 print (sentences)


Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [34]:
import numpy as np


def vander_matrix(ip_vector, n, increasing=False):
    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in ip_vector for i in range(n)]).reshape(ip_vector.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in ip_vector for i in range(n)]).reshape(ip_vector.size,n)
    
    return op_matx

 
c = int(input("Enter the number of columns:")) 
 
print("Enter the entries in a single line (separated by space): ") 
  
# User input of entries in a  
# single line separated by space 
entries = list(map(int, input().split())) 
  
# For printing the matrix 
inputvector = np.array(entries).reshape(c) 
print(inputvector)
no_col_opmat=int(input("Enter no_col_opmat:"))

op_matx_dec_order = vander_matrix(inputvector,no_col_opmat,False)
op_matx_inc_order = vander_matrix(inputvector,no_col_opmat,True)

print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",no_col_opmat,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")



Enter the number of columns:2
Enter the entries in a single line (separated by space): 
1 5
[1 5]
Enter no_col_opmat:8
The input array is: [1 5] 

Number of columns in output matrix should be: 8 

Vander matrix of the input array in decreasing order of powers:

 [[    1     1     1     1     1     1     1     1]
 [78125 15625  3125   625   125    25     5     1]] 

Vander matrix of the input array in increasing order of powers:

 [[    1     1     1     1     1     1     1     1]
 [    1     5    25   125   625  3125 15625 78125]] 

